# Generated by Django 4.1.6 on 2023-03-16 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_todo_created_at_alter_todo_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('42680ab2-9805-471b-88e0-00b2b8dfbeef'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('client_name', models.CharField(max_length=100)),
                ('client_description', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
